#!/usr/bin/env python3
"""Turn the bandit CSV from crl_labs.py into a self-contained HTML report.
Python 3 standard library only. Run: python3 examples/analyze_crl.py bandit.csv --out report.html
Curves show each seed and the across-seed mean. Tables show sample SD, NOT a CI.
"""
import argparse
import csv
import html
import math
import statistics
from collections import defaultdict
from pathlib import Path

METRICS = {'window_reward':'窗口平均奖励', 'choice_b':'选择 B 的比例',
           'q_a':'窗口末 Q(A)', 'q_b':'窗口末 Q(B)'}
METHODS = {'sample_mean':'样本平均', 'constant_step':'常数步长'}
COLORS = {'sample_mean':'#8493aa', 'constant_step':'#2563eb'}


def load_rows(path):
    with path.open(encoding='utf-8-sig', newline='') as f:
        rows = list(csv.DictReader(f))
    if not rows:
        raise ValueError('Empty CSV.')
    seen, configs = set(), set()
    fields = ('total_steps','switch_step','alpha','epsilon')
    for row in rows:
        if row.get('lab') != 'bandit' or not all(row.get(k) for k in fields):
            raise ValueError('Use the bandit CSV generated by the accompanying crl_labs.py.')
        for k in ('seed','step','window_steps','total_steps','switch_step'):
            row[k] = int(row[k])
        for k in ('value','alpha','epsilon'):
            row[k] = float(row[k])
        if row['method'] not in METHODS or row['metric'] not in METRICS:
            raise ValueError('Unknown method or metric.')
        if not math.isfinite(row['value']) or not 0 <= row['value'] <= 1:
            raise ValueError('Invalid bandit metric.')
        if not 0 < row['window_steps'] <= row['step'] <= row['total_steps']:
            raise ValueError('Invalid window length.')
        key = (row['seed'],row['method'],row['step'],row['metric'])
        if key in seen:
            raise ValueError('Duplicate seed/method/step/metric; do not concatenate duplicate runs.')
        seen.add(key)
        configs.add(tuple(row[k] for k in fields))
    if len(configs) != 1:
        raise ValueError('Each report expects one configuration; generate separate reports for comparisons.')
    total, switch, alpha, epsilon = next(iter(configs))
    if not 0 < switch < total or not 0 < alpha <= 1 or not 0 <= epsilon <= 1:
        raise ValueError('Invalid run configuration.')
    seeds = sorted({r['seed'] for r in rows})
    ends = sorted({r['step'] for r in rows})
    expected = {(s,m,t,k) for s in seeds for m in METHODS for t in ends for k in METRICS}
    if seen != expected or ends[-1] != total or switch not in ends:
        raise ValueError('Incomplete grid of seeds, methods, windows or metrics.')
    previous = 0
    for end in ends:
        if any(r['window_steps'] != end-previous for r in rows if r['step']==end):
            raise ValueError('Window lengths do not match successive endpoints.')
        previous = end
    return rows


def weighted_reward(rows):
    return sum(r['value']*r['window_steps'] for r in rows)/sum(r['window_steps'] for r in rows)


def render(rows, filename):
    total, switch = rows[0]['total_steps'], rows[0]['switch_step']
    seeds = sorted({r['seed'] for r in rows})
    steps = sorted({r['step'] for r in rows})
    post = [t for t in steps if t>switch]
    early_end = post[min(4,len(post)-1)]
    phases = [('变化前',lambda r:r['step']<=switch),
              (f'变化后起始段（{switch+1}–{early_end} 步）',lambda r:switch<r['step']<=early_end)]
    if early_end<total:
        phases.append((f'变化后剩余段（{early_end+1}–{total} 步）',lambda r:r['step']>early_end))
    phases.append(('全程',lambda r:True))
    def mean_sd(values):
        avg = statistics.mean(values)
        sd = f'{statistics.stdev(values):.3f}' if len(values)>1 else '—（单 seed）'
        return f'{avg:.3f} ± {sd}'
    def curve(series):
        return ' '.join(f'{40+step/total*340:.2f},{215-value*170:.2f}' for step,value in series)
    charts = []
    for metric, label in METRICS.items():
        svg = [f'<svg viewBox="0 0 400 265" role="img" aria-label="{label}">']
        for value in (0,.25,.5,.75,1):
            y = 215-value*170
            svg.append(f'<path d="M40 {y}H380" stroke="#e2e8f0"/><text x="4" y="{y+4}">{value:g}</text>')
        x = 40+switch/total*340
        svg.append(f'<path d="M{x} 35V215" stroke="#b88744" stroke-dasharray="5 5"/>')
        for method in METHODS:
            group = [r for r in rows if r['metric']==metric and r['method']==method]
            by_step = defaultdict(list)
            for seed in seeds:
                single = sorted((r['step'],r['value']) for r in group if r['seed']==seed)
                svg.append(f'<polyline points="{curve(single)}" fill="none" stroke="{COLORS[method]}" opacity=".13" stroke-width="1"/>')
                for t,value in single:
                    by_step[t].append(value)
            average = sorted((t,statistics.mean(v)) for t,v in by_step.items())
            svg.append(f'<polyline points="{curve(average)}" fill="none" stroke="{COLORS[method]}" stroke-width="2.8"/>')
        for tick in sorted({0,switch,total}):
            svg.append(f'<text x="{40+tick/total*340}" y="239" text-anchor="middle">{tick}</text>')
        svg.append('<text x="210" y="261" text-anchor="middle">交互步数</text></svg>')
        charts.append(f'<section><h2>{label}</h2>'+''.join(svg)+'</section>')
    table, per_seed = [], []
    for label, select in phases:
        cells = []
        for method in METHODS:
            values = []
            for seed in seeds:
                selected = [r for r in rows if r['metric']=='window_reward' and r['method']==method and r['seed']==seed and select(r)]
                val = weighted_reward(selected)
                values.append(val)
                per_seed.append(f'<tr><td>{seed}</td><td>{METHODS[method]}</td><td>{label}</td><td>{val:.4f}</td></tr>')
            cells.append(f'<td>{mean_sd(values)}</td>')
        table.append(f'<tr><td>{label}</td>'+''.join(cells)+'</tr>')
    config = f"α={rows[0]['alpha']} · ε={rows[0]['epsilon']} · {len(seeds)} seeds · {total} 步 · {switch} 步后切换"
    return '''<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>CRL 第一个实验 · Bandit 报告</title><link rel="icon" href="data:,"><style>
body{font:15px/1.8 system-ui,sans-serif;color:#334155;max-width:940px;margin:40px auto;padding:0 20px;background:#f9fafc}h1{font-size:28px}h2{font-size:18px}section{background:white;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:18px 0}svg{width:100%;font:12px system-ui;fill:#64748b}.plots{display:grid;grid-template-columns:1fr 1fr;gap:14px}.plots section{margin:0}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:10px;text-align:left;border-bottom:1px solid #e2e8f0}.scroll{overflow:auto}p{color:#52617a}.blue{color:#2563eb}.grey{color:#8493aa}li{margin:9px 0}@media(max-width:660px){.plots{grid-template-columns:1fr}body{padding:0 12px}h1{font-size:23px}}
@media print{body{background:white;margin:0}.plots{display:block}section{break-inside:avoid}.scroll{overflow:visible}}
</style></head><body><main><h1>变化以后，学习器怎样适应？</h1>''' + f'''
<p>{config}<br>输入文件：{html.escape(filename)}</p>
<p><span class="blue">━ 常数步长</span>　<span class="grey">━ 样本平均</span>。粗线为跨 seed 均值，浅线为每个 seed；竖虚线为切换。Q 值是窗口末快照，奖励和动作比例是窗口内均值。</p>
<div class="plots">{''.join(charts)}</div>
<section><h2>奖励分段摘要</h2><p>每个 seed 先按窗口长度加权，再跨 seed 汇总。表中 ± 是样本标准差，不是置信区间。起始段取切换后的前 5 个记录窗口，默认共 500 步。</p>
<div class="scroll"><table><thead><tr><th>阶段</th><th>样本平均 · 均值 ± SD</th><th>常数步长 · 均值 ± SD</th></tr></thead><tbody>{''.join(table)}</tbody></table></div></section>
<section><h2>按这个顺序解释</h2><ol><li>奖励在哪里下降、恢复？两个方法在起始段与剩余段的排序一致吗？</li><li>切换后选 B 的比例是否提高？Q(B) 何时高于 Q(A)？只看奖励不能回答这两问。</li><li>改变 α 后，跟踪速度与估值波动怎样变化？均值趋势在大多数 seed 上都出现吗？</li><li>写清本实验只研究奖励反转下的估计与探索，不含深度网络、技能或记忆学习。</li></ol></section>
<details><summary>展开每个 seed 的摘要</summary><div class="scroll"><table><thead><tr><th>Seed</th><th>方法</th><th>阶段</th><th>平均奖励</th></tr></thead><tbody>{''.join(per_seed)}</tbody></table></div></details>
</main></body></html>'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('csv', type=Path)
    parser.add_argument('--out', type=Path, default=Path('bandit-report.html'))
    args = parser.parse_args()
    try:
        rows = load_rows(args.csv)
        document = render(rows, args.csv.name)
        with args.out.open('x', encoding='utf-8') as f:
            f.write(document)
    except (OSError, ValueError, KeyError) as exc:
        parser.exit(1, f'Cannot create report: {exc}\nUse a new --out name if the report already exists.\n')
    print(f'{args.out.resolve()}\nOpen this HTML file in your browser. No server or plotting package needed.')


if __name__ == '__main__':
    main()
